version: "3.8"
services:
  postgres_capstone:
    image: "postgres:13"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata_purwadika:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER= ${DB_USERS}
      - POSTGRES_PASSWORD= ${DB_PASSWORD}
      - POSTGRES_DB= ${DB_NAME}

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres_capstone
    ports:
      - 8080:8080
