services:
  postgres_capstone:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - pgdata_purwadika:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    image: adminer
    depends_on:
      - postgres_capstone
    ports:
      - "8080:8080"

volumes:
  pgdata_purwadika:
